name: Build the Docker Image and Push it to AWS ECR

on:
  push:
    branches: [main]

jobs:
  build-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v2

    # Step 2: Configure AWS Credentials using OIDC
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::680343405290:role/github-actions-deploy  # IAM role to assume
        aws-region: us-east-1

    # Step 3: Login to AWS ECR
    - name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    # Step 4: Build and Push the Docker Image to ECR
    - name: Build and Push Image to ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}  # ECR registry URL from the login step
        ECR_REPOSITORY: crewmeister-challenge  # Name of the ECR repository
        IMAGE_TAG: latest  # Tag for the Docker image
      run: |
        # Build the Docker image
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        
        # Push the Docker image to ECR
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
